### ISSUE TITLE
Unable to use listen:true on model.of(context,true)

### ISSUE THREAD

**Issue by PrideFafy** [nyakaz73/reactive_store#1]
`E/flutter (32146): [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: 'package:provider/src/provider.dart': Failed assertion: line 242 pos 7: 'context.owner.debugBuilding ||
E/flutter (32146):           listen == false ||
E/flutter (32146):           debugIsInInheritedProviderUpdate': Tried to listen to a value exposed with provider, from outside of the widget tree.
E/flutter (32146): 
E/flutter (32146): This is likely caused by an event handler (like a button's onPressed) that called
E/flutter (32146): Provider.of without passing `listen: false`.
E/flutter (32146): 
E/flutter (32146): To fix, write:
E/flutter (32146): Provider.of<StoreModel>(context, listen: false);
E/flutter (32146): 
E/flutter (32146): It is unsupported because may pointlessly rebuild the widget associated to the
E/flutter (32146): event handler, when the widget tree doesn't care about the value.
E/flutter (32146): 
E/flutter (32146): The context used was: OrderDialog(dependencies: [MediaQuery], state: _OrderDialogState#13096)
E/flutter (32146): 
E/flutter (32146): #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:46:39)
E/flutter (32146): #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
E/flutter (32146): #2      Provider.of (package:provider/src/provider.dart:242:7)
E/flutter (32146): #3      StoreModel.of (package:reactivestore/model/store_model.dart:17:21)
E/flutter (32146): #4      _OrderDialogState.addOrder (package:salesforceapp/ui/screens/order_dialog.dart:196:23)
E/flutter (32146): #5      _OrderDialogState.build.<anonymous closure> (package:salesforceapp/ui/screens/order_dialog.dart:146:35)
E/flutter (32146): #6      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:992:19)
E/flutter (32146): #7      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:1098:38)
E/flutter (32146): #8      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:184:24)
E/flutter (32146): #9      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:524:11)
E/flutter (32146): #10     BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:284:5)
E/flutter (32146): #11     BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:256:7)
E/flutter (32146): #12     GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:158:27)
E/flutter (32146): #13     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:224:20)
E/flutter (32146): #14     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:200:22)
E/flutter (32146): #15     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:158:7)
E/flutter (32146): #16     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:104:7)
E/flutter (32146): #17     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:88:7)
E/flutter (32146): #18     _rootRunUnary (dart:async/zone.dart:1206:13)
E/flutter (32146): #19     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter (32146): #20     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
E/flutter (32146): #21     _invoke1 (dart:ui/hooks.dart:267:10)
E/flutter (32146): #22     _dispatchPointerDataPacket (dart:ui/hooks.dart:176:5)`

**Comment by nyakaz73** [comment]
You can use **model.of(context,false)** with listen parameter set to **false**, since you are calling it from an event handler.  It will automatically update your UI where there is need be.
Hope this helps :)
